name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Test
        run: |
          npm run test

  deploy:
    needs: build
    if: ${{ github.event.pull_request.merged || github.event_name == 'push' }}
    uses: ./.github/workflows/cd.yml
    secrets: inherit
