name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout "build"
      run: |
        git checkout -b build

    - name: Build
      run: |
        npm install
        npm run build
        git config user.email $GIT_AUTHOR_EMAIL
        git config user.name $GITHUB_ACTOR
        git add .
        git commit -m "Build"
        git push -fu origin build
      env:
        GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        JSON_API_BASE_URL: ${{ secrets.JSON_API_BASE_URL }}
